CREATE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;
CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;
SHOW SCHEMAS;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    CITY STRING,
    STATE STRING,
    SIGNUP_DATE STRING
);

CREATE OR REPLACE TABLE PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    UNIT_PRICE STRING
);

CREATE OR REPLACE TABLE ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY STRING,
    ORDER_DATE STRING,
    AMOUNT STRING
);

SHOW TABLES;

SELECT COUNT(*) 
FROM BRONZE.CUSTOMERS_RAW;

SELECT *
FROM BRONZE.CUSTOMERS_RAW
LIMIT 5;

SELECT COUNT(*) FROM BRONZE.PRODUCTS_RAW;
-- SELECT COUNT(*) FROM BRONZE.ORDERS_RAW;
SELECT COUNT(*)
FROM BRONZE.PRODUCTS_RAW;
TRUNCATE TABLE BRONZE.orders_RAW;
SELECT COUNT(*)
FROM BRONZE.ORDERS_RAW;
TRUNCATE TABLE BRONZE.Products_RAW;
SELECT COUNT(*)
FROM BRONZE.PRODUCTS_RAW;

USE SCHEMA SILVER;
CREATE OR REPLACE TABLE CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    TO_DATE(SIGNUP_DATE) AS SIGNUP_DATE
FROM BRONZE.CUSTOMERS_RAW
WHERE CUSTOMER_ID <> 'customer_id';
SELECT COUNT(*)
FROM CUSTOMERS;
USE SCHEMA SILVER;
CREATE OR REPLACE TABLE PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TO_NUMBER(UNIT_PRICE) AS UNIT_PRICE
FROM BRONZE.PRODUCTS_RAW;
SELECT COUNT(*)
FROM PRODUCTS;

CREATE OR REPLACE TABLE ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_NUMBER(QUANTITY) AS QUANTITY,
    TO_DATE(ORDER_DATE) AS ORDER_DATE,
    TO_NUMBER(AMOUNT) AS AMOUNT
FROM BRONZE.ORDERS_RAW;
SELECT COUNT(*)
FROM ORDERS;

USE SCHEMA GOLD;
CREATE OR REPLACE TABLE CUSTOMER_SALES AS
SELECT
    CUSTOMER_ID,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(AMOUNT) AS TOTAL_REVENUE,
    AVG(AMOUNT) AS AVG_ORDER_VALUE
FROM SILVER.ORDERS
GROUP BY CUSTOMER_ID;

SELECT *
FROM CUSTOMER_SALES
LIMIT 10;

CREATE OR REPLACE TABLE PRODUCT_SALES AS
SELECT
    PRODUCT_ID,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(AMOUNT) AS TOTAL_REVENUE
FROM SILVER.ORDERS
GROUP BY PRODUCT_ID;

SELECT *
FROM PRODUCT_SALES
LIMIT 10;
CREATE OR REPLACE TABLE MONTHLY_REVENUE AS
SELECT
    DATE_TRUNC('MONTH', ORDER_DATE) AS MONTH,
    SUM(AMOUNT) AS REVENUE
FROM SILVER.ORDERS
GROUP BY MONTH
ORDER BY MONTH;
SELECT *
FROM MONTHLY_REVENUE;
SHOW TABLES;
SELECT *
FROM GOLD.CUSTOMER_SALES
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
CREATE OR REPLACE VIEW VW_CUSTOMER_ANALYTICS AS
SELECT *
FROM CUSTOMER_SALES;
CREATE OR REPLACE VIEW VW_PRODUCT_ANALYTICS AS
SELECT *
FROM PRODUCT_SALES;
CREATE OR REPLACE VIEW VW_REVENUE_DASHBOARD AS
SELECT *
FROM MONTHLY_REVENUE;
SHOW VIEWS;
SHOW WAREHOUSES;

--Adding star schema : 1. Create DIM_CUSTOMERS
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    SIGNUP_DATE
FROM SILVER.CUSTOMERS;

SELECT COUNT(*)
FROM DIM_CUSTOMERS;

-- 2. Create DIM_Products
CREATE OR REPLACE TABLE DIM_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
FROM SILVER.PRODUCTS;
SELECT COUNT(*)
FROM DIM_PRODUCTS;

--Create FACT_ORDERS
CREATE OR REPLACE TABLE FACT_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ORDER_DATE,
    QUANTITY,
    AMOUNT
FROM SILVER.ORDERS;

SELECT COUNT(*)
FROM FACT_ORDERS;

--validating Relationship (checking for orphan customer)

SELECT COUNT(*)
FROM FACT_ORDERS F
LEFT JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

--Check for orphan products:

SELECT COUNT(*)
FROM FACT_ORDERS F
LEFT JOIN DIM_PRODUCTS P
ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

---Check for orphan orders:

SELECT COUNT(*)
FROM FACT_ORDERS F
LEFT JOIN DIM_PRODUCTS P
ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

SHOW TABLES;
--Validating data quality
--step 1
USE DATABASE RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS DATA_QUALITY;

--Step 2: Create a DQ Results Table
--This stores the results of quality checks.
USE SCHEMA DATA_QUALITY;

CREATE OR REPLACE TABLE DQ_RESULTS (
    CHECK_NAME STRING,
    TABLE_NAME STRING,
    FAILED_RECORDS NUMBER,
    CHECK_TIMESTAMP TIMESTAMP
);
--Step 3: Check for Null Customer IDs
SELECT COUNT(*) AS FAILED_RECORDS
FROM GOLD.FACT_ORDERS
WHERE CUSTOMER_ID IS NULL;

--Step 4: Store Result
INSERT INTO DQ_RESULTS
SELECT
    'NULL_CUSTOMER_ID',
    'FACT_ORDERS',
    COUNT(*),
    CURRENT_TIMESTAMP()
FROM GOLD.FACT_ORDERS
WHERE CUSTOMER_ID IS NULL;

--Step 5: Check Duplicate Customers
SELECT
    CUSTOMER_ID,
    COUNT(*)
FROM GOLD.DIM_CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- Step 6 : store result
INSERT INTO DQ_RESULTS
SELECT
    'DUPLICATE_CUSTOMER',
    'DIM_CUSTOMERS',
    COUNT(*),
    CURRENT_TIMESTAMP()
FROM
(
    SELECT CUSTOMER_ID
    FROM GOLD.DIM_CUSTOMERS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(*) > 1
);
--Step 7: Check Orphan Customers
SELECT COUNT(*)
FROM GOLD.FACT_ORDERS F
LEFT JOIN GOLD.DIM_CUSTOMERS C
ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

--Step 8: Store Orphan Check Result

INSERT INTO DQ_RESULTS
SELECT
    'ORPHAN_CUSTOMER',
    'FACT_ORDERS',
    COUNT(*),
    CURRENT_TIMESTAMP()
FROM GOLD.FACT_ORDERS F
LEFT JOIN GOLD.DIM_CUSTOMERS C
ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

--Step 9: Check Orphan Products

SELECT COUNT(*)
FROM GOLD.FACT_ORDERS F
LEFT JOIN GOLD.DIM_PRODUCTS P
ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

--Step 10: Negative Revenue Check
SELECT COUNT(*)
FROM GOLD.FACT_ORDERS
WHERE AMOUNT < 0;

SELECT *
FROM DATA_QUALITY.DQ_RESULTS;

---Pipeline Audit Logging

CREATE OR REPLACE TABLE PIPELINE_AUDIT (
    PIPELINE_NAME STRING,
    TABLE_NAME STRING,
    RECORD_COUNT NUMBER,
    LOAD_TIMESTAMP TIMESTAMP,
    STATUS STRING
);

--- Stream

USE DATABASE RETAIL_DB;
USE SCHEMA BRONZE;

--Step 1: Create a Stream
CREATE OR REPLACE STREAM ORDERS_RAW_STREAM
ON TABLE ORDERS_RAW;

SHOW STREAMS;

--Step 2: Check Stream Contents
SELECT * FROM ORDERS_RAW_STREAM;

--Step 3: Insert New Data into ORDERS_RAW

INSERT INTO ORDERS_RAW
VALUES
('ORD10001','C001','P001','2','2026-06-23','500'),
('ORD10002','C002','P002','1','2026-06-23','300');

--Now check the stream:
SELECT * FROM ORDERS_RAW_STREAM;

--Step 4: Load Only New Records into SILVER
INSERT INTO SILVER.ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    AMOUNT
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_NUMBER(QUANTITY),
    TO_DATE(ORDER_DATE),
    TO_NUMBER(AMOUNT)
FROM BRONZE.ORDERS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

SELECT COUNT(*) FROM SILVER.ORDERS;

--Create Streams for 2 more 

CREATE STREAM CUSTOMERS_RAW_STREAM
ON TABLE CUSTOMERS_RAW;

CREATE STREAM PRODUCTS_RAW_STREAM
ON TABLE PRODUCTS_RAW;

SHOW STREAMS;

--Create Incremental Load Statements
-- for Customers 
INSERT INTO SILVER.CUSTOMERS
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    SIGNUP_DATE
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    TO_DATE(SIGNUP_DATE)
FROM BRONZE.CUSTOMERS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

--For Products
INSERT INTO SILVER.PRODUCTS
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TO_NUMBER(UNIT_PRICE)
FROM BRONZE.PRODUCTS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

-- for Orders

INSERT INTO SILVER.ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    AMOUNT
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_NUMBER(QUANTITY),
    TO_DATE(ORDER_DATE),
    TO_NUMBER(AMOUNT)
FROM BRONZE.ORDERS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

-- Let's implement(check) incremental loading for all 3 Silver tables using the streams created
-- Insert values For customer

INSERT INTO BRONZE.CUSTOMERS_RAW
VALUES
('C999','Test Customer','Pune','Maharashtra','2026-06-25');

--Step 2: Verify Streams Captured the Changes

SELECT * FROM BRONZE.CUSTOMERS_RAW_STREAM;

--Step 3:Verify Incremental Load Customers

SELECT *
FROM SILVER.CUSTOMERS
WHERE CUSTOMER_ID = 'C999';

--Insert values For customer

INSERT INTO BRONZE.PRODUCTS_RAW
VALUES
('P999','Test Product','Testing','100');

--Step 2: Verify Streams Captured the Changes

Select * from BRONZE.PRODUCTS_RAW_STREAM;

--Step 3:Verify Incremental Load Customers

SELECT *
FROM SILVER.PRODUCTS
WHERE PRODUCT_ID = 'P999';

-----Insert values For customer

INSERT INTO BRONZE.ORDERS_RAW
VALUES
('O999','C999','P999','2','2026-06-25','200');

---Step 2: Verify Streams Captured the Changes

SELECT * FROM BRONZE.ORDERS_RAW_STREAM;

---Step 3:Verify Incremental Load Customers

SELECT *
FROM SILVER.ORDERS
WHERE ORDER_ID = 'O999';

---Creating TASK

--Task 1: Customers Incremental Load

CREATE OR REPLACE TASK LOAD_CUSTOMERS_TO_SILVER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.CUSTOMERS_RAW_STREAM')
AS
INSERT INTO SILVER.CUSTOMERS
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    SIGNUP_DATE
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    TO_DATE(SIGNUP_DATE)
FROM BRONZE.CUSTOMERS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

---Task 2: Products Incremental Load

CREATE OR REPLACE TASK LOAD_PRODUCTS_TO_SILVER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.PRODUCTS_RAW_STREAM')
AS
INSERT INTO SILVER.PRODUCTS
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TO_NUMBER(UNIT_PRICE)
FROM BRONZE.PRODUCTS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

---Task 3: Orders Incremental Load

CREATE OR REPLACE TASK LOAD_ORDERS_TO_SILVER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.ORDERS_RAW_STREAM')
AS
INSERT INTO SILVER.ORDERS
(
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    ORDER_DATE,
    AMOUNT
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    TO_NUMBER(QUANTITY),
    TO_DATE(ORDER_DATE),
    TO_NUMBER(AMOUNT)
FROM BRONZE.ORDERS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';

--Enable the Tasks
--A newly created task is suspended by default.

ALTER TASK LOAD_CUSTOMERS_TO_SILVER RESUME;
ALTER TASK LOAD_PRODUCTS_TO_SILVER RESUME;
ALTER TASK LOAD_ORDERS_TO_SILVER RESUME;

SHOW TASKS;
--checking is task working 

INSERT INTO BRONZE.CUSTOMERS_RAW
VALUES
('C1000','Auto Customer','Pune','Maharashtra','2026-06-25');

SELECT *
FROM SILVER.CUSTOMERS
WHERE CUSTOMER_ID = 'C1000';
----------------------------------------------------------------------

---Creating Stored procedure

CREATE OR REPLACE PROCEDURE LOAD_CUSTOMERS_PROC()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    INSERT INTO SILVER.CUSTOMERS
    (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        STATE,
        SIGNUP_DATE
    )
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        STATE,
        TO_DATE(SIGNUP_DATE)
    FROM BRONZE.CUSTOMERS_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    RETURN 'CUSTOMERS LOADED SUCCESSFULLY';

END;
$$;

---Execute the Procedure

CALL LOAD_CUSTOMERS_PROC();

---                                   Test It  (stored procedure)
---Insert a new customer into Bronze:

INSERT INTO BRONZE.CUSTOMERS_RAW
VALUES
('C2000','Procedure Test','Pune','Maharashtra','2026-06-25');

---Verify stream has data:

SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMERS_RAW_STREAM');

---Run procedure:

CALL LOAD_CUSTOMERS_PROC();

---Verify Silver:

SELECT *
FROM SILVER.CUSTOMERS
WHERE CUSTOMER_ID = 'C2000';

---for products 

CREATE OR REPLACE PROCEDURE LOAD_PRODUCTS_PROC()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    INSERT INTO SILVER.PRODUCTS
    (
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        UNIT_PRICE
    )
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        TO_NUMBER(UNIT_PRICE)
    FROM BRONZE.PRODUCTS_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    RETURN 'PRODUCTS LOADED SUCCESSFULLY';

END;
$$;

CALL LOAD_PRODUCTS_PROC();

---orders procedure 

CREATE OR REPLACE PROCEDURE LOAD_ORDERS_PROC()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    INSERT INTO SILVER.ORDERS
    (
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        QUANTITY,
        ORDER_DATE,
        AMOUNT
    )
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        TO_NUMBER(QUANTITY),
        TO_DATE(ORDER_DATE),
        TO_NUMBER(AMOUNT)
    FROM BRONZE.ORDERS_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    RETURN 'ORDERS LOADED SUCCESSFULLY';

END;
$$;